[package]
name        = "aztlan_profile"
version     = "0.1.0"
edition     = "2021"
type        = "contract"
description = "Aztlan Profile ZK Contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "alpha-testnet", directory = "noir-projects/aztec-nr/aztec" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "alpha-testnet", directory = "noir-projects/aztec-nr/compressed-string" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "alpha-testnet", directory = "noir-projects/aztec-nr/authwit" }

