
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import AztlanProfileRegistryContractArtifactJson from '../../target/aztlan_contract-AztlanProfileRegistry.json' with { type: 'json' };
export const AztlanProfileRegistryContractArtifact = loadContractArtifact(AztlanProfileRegistryContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract AztlanProfileRegistry;
 */
export class AztlanProfileRegistryContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, AztlanProfileRegistryContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, AztlanProfileRegistryContract.artifact, wallet) as Promise<AztlanProfileRegistryContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<AztlanProfileRegistryContract>(PublicKeys.default(), wallet, AztlanProfileRegistryContractArtifact, AztlanProfileRegistryContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<AztlanProfileRegistryContract>(publicKeys, wallet, AztlanProfileRegistryContractArtifact, AztlanProfileRegistryContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof AztlanProfileRegistryContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<AztlanProfileRegistryContract['methods'][M]>
  ) {
    return new DeployMethod<AztlanProfileRegistryContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      AztlanProfileRegistryContractArtifact,
      AztlanProfileRegistryContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return AztlanProfileRegistryContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(AztlanProfileRegistryContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'username_to_address' | 'profile_id_of' | 'token_uri' | 'profile_burned' | 'profile_visibility' | 'blocked_addresses' | 'has_profile' | 'profile_created_at' | 'profile_last_updated' | 'username_last_changed' | 'username_change_count' | 'recovery_address' | 'recovery_requested_at' | 'social_verifier_contract' | 'quest_points_contract' | 'privacy_settings_contract' | 'kyc_verifier_contract' | 'admin' | 'total_profiles' | 'total_burned_profiles' | 'next_profile_id' | 'username_change_cooldown' | 'recovery_delay' | 'profile_creation_paused' | 'burn_enabled'> {
      return {
        username_to_address: {
      slot: new Fr(1n),
    },
profile_id_of: {
      slot: new Fr(2n),
    },
token_uri: {
      slot: new Fr(3n),
    },
profile_burned: {
      slot: new Fr(4n),
    },
profile_visibility: {
      slot: new Fr(5n),
    },
blocked_addresses: {
      slot: new Fr(6n),
    },
has_profile: {
      slot: new Fr(7n),
    },
profile_created_at: {
      slot: new Fr(8n),
    },
profile_last_updated: {
      slot: new Fr(9n),
    },
username_last_changed: {
      slot: new Fr(10n),
    },
username_change_count: {
      slot: new Fr(11n),
    },
recovery_address: {
      slot: new Fr(12n),
    },
recovery_requested_at: {
      slot: new Fr(13n),
    },
social_verifier_contract: {
      slot: new Fr(14n),
    },
quest_points_contract: {
      slot: new Fr(15n),
    },
privacy_settings_contract: {
      slot: new Fr(16n),
    },
kyc_verifier_contract: {
      slot: new Fr(17n),
    },
admin: {
      slot: new Fr(18n),
    },
total_profiles: {
      slot: new Fr(19n),
    },
total_burned_profiles: {
      slot: new Fr(20n),
    },
next_profile_id: {
      slot: new Fr(21n),
    },
username_change_cooldown: {
      slot: new Fr(22n),
    },
recovery_delay: {
      slot: new Fr(23n),
    },
profile_creation_paused: {
      slot: new Fr(24n),
    },
burn_enabled: {
      slot: new Fr(25n),
    }
      } as ContractStorageLayout<'username_to_address' | 'profile_id_of' | 'token_uri' | 'profile_burned' | 'profile_visibility' | 'blocked_addresses' | 'has_profile' | 'profile_created_at' | 'profile_last_updated' | 'username_last_changed' | 'username_change_count' | 'recovery_address' | 'recovery_requested_at' | 'social_verifier_contract' | 'quest_points_contract' | 'privacy_settings_contract' | 'kyc_verifier_contract' | 'admin' | 'total_profiles' | 'total_burned_profiles' | 'next_profile_id' | 'username_change_cooldown' | 'recovery_delay' | 'profile_creation_paused' | 'burn_enabled'>;
    }
    

  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** block_address(address_to_block: struct) */
    block_address: ((address_to_block: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** burn_profile() */
    burn_profile: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** complete_recovery(lost_address: struct, new_address: struct) */
    complete_recovery: ((lost_address: AztecAddressLike, new_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_profile(username_hash: field, token_uri_hash: field) */
    create_profile: ((username_hash: FieldLike, token_uri_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_address_by_username(username_hash: field) */
    get_address_by_username: ((username_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_kyc_verifier_contract() */
    get_kyc_verifier_contract: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_privacy_settings_contract() */
    get_privacy_settings_contract: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_profile_id(user: struct) */
    get_profile_id: ((user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_profile_visibility(user: struct) */
    get_profile_visibility: ((user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_quest_points_contract() */
    get_quest_points_contract: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_recovery_address(user: struct) */
    get_recovery_address: ((user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_social_verifier_contract() */
    get_social_verifier_contract: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_token_uri(user: struct) */
    get_token_uri: ((user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_burned_profiles() */
    get_total_burned_profiles: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_profiles() */
    get_total_profiles: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** has_profile(user: struct) */
    has_profile: ((user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initiate_recovery(lost_address: struct) */
    initiate_recovery: ((lost_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_blocked(profile_owner: struct, blocked_address: struct) */
    is_blocked: ((profile_owner: AztecAddressLike, blocked_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_burn_enabled() */
    is_burn_enabled: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_profile_burned(user: struct) */
    is_profile_burned: ((user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_username_available(username_hash: field) */
    is_username_available: ((username_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint(username_hash: field, token_uri_hash: field) */
    mint: ((username_hash: FieldLike, token_uri_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** pause_profile_creation() */
    pause_profile_creation: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_kyc_verifier_contract(kyc_verifier: struct) */
    set_kyc_verifier_contract: ((kyc_verifier: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_privacy_settings_contract(privacy_settings: struct) */
    set_privacy_settings_contract: ((privacy_settings: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_profile_visibility(visibility: field) */
    set_profile_visibility: ((visibility: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_quest_points_contract(quest_points: struct) */
    set_quest_points_contract: ((quest_points: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_recovery_address(recovery: struct) */
    set_recovery_address: ((recovery: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_social_verifier_contract(social_verifier: struct) */
    set_social_verifier_contract: ((social_verifier: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_notes() */
    sync_notes: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** toggle_burn_enabled() */
    toggle_burn_enabled: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_admin(new_admin: struct) */
    transfer_admin: ((new_admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** unblock_address(address_to_unblock: struct) */
    unblock_address: ((address_to_unblock: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** unpause_profile_creation() */
    unpause_profile_creation: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_token_uri(new_uri_hash: field) */
    update_token_uri: ((new_uri_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_username(old_username_hash: field, new_username_hash: field) */
    update_username: ((old_username_hash: FieldLike, new_username_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
